### ISSUE TITLE
Model Exceptions after the ruby library's Errors

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#24]
* Differentiate types by http status codes
* make them print out YAML in stack trace (the format needs to be consistent with the Ruby library)
* Do #23

**Comment by mmazi** [comment]
Port two relevant existing Ruby tests in errors_spec.rb: `is raised on unexpected error` and `contains full details for api error`.

**Comment by mmazi** [comment]
A few questions about the YAML output:

1. What is the first line (eg. `CurrencyCloud::BadRequestError`) and how should we handle this in Java since it seems Ruby-specific?
1. Similarly, what to do with `UnexpectedException::inner_error`?
1. What is response::request_id?
1. Is it OK to use double-quoted strings (instead of plain strings)?
1. Is the exact `response::date` format important?

**Comment by mmazi** [comment]
TODO: readme

**Comment by mmazi** [comment]
An example of current formatting:

```yaml
---
platform: "Java 1.7.0_51 (Oracle Corporation)"
request:
  parameters:
    login_id: "non-existent-login-id"
    api_key: "ef0fd50fca1fb14c1fab3a8436b9ecb57528f0"
  verb: "post"
  url: "http://localhost:5555/v2/authenticate/api"
response:
  status_code: 400
  date: "Tue, 2 Jun 2015 13:54:17 CEST"
error_code: "auth_invalid_user_login_details"
errors:
- field: "api_key"
  code: "api_key_length_is_invalid"
  message: "api_key should be 64 character(s) long"
  params:
    length: 64
```
